services:
  app:
    build:
      context: .
      dockerfile: DockerfileApp
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Ensures code changes are reflected in the container
    environment:
      - ENV_VAR=example
      - STREAMLIT_SERVER_RUN_ON_SAVE=true  # Automatically reloads the app when code changes
      - STREAMlIT_HEADLESS=true
      - STREAMlIT_ALLOW_RUN_ON_SAVE=true
      - STREAMlIT_FAST_RERUNS=true
      - STREAMlIT_FILE_WATCHER_TYPE="poll"